### ISSUE TITLE
Quoting of strings may be needed

### ISSUE THREAD

**Issue by triska** [aarroyoc/scryer-playground#1]
Example:

<pre>
<b>?- Cs = "hello".</b>
error(syntax_error(incomplete_reduction),read_term/3:3). 
</pre>

**Comment by aarroyoc** [comment]
Yes, it was needed. Thanks for noticing!

**Comment by triska** [comment]
Awesome, thank you! You can make Scryer use double quoted lists for string by using the write option `double_quotes(true)`!

**Comment by aarroyoc** [comment]
Now, I also set `double_quotes(true)` in `write_term/2`
