### ISSUE TITLE
Are libraries supported in Scryer Playground?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [aarroyoc/scryer-playground#11]
Tried to test:
```
:- use_module(library(between)).
:- use_module(library(time)).

?- time((between(1,1000000,_), fail; true)).
```
https://play.scryer.pl/

I got this currious error:

![286333308-fc12c1af-3dee-4fe8-ba13-70ec7ad1323a](https://github.com/aarroyoc/scryer-playground/assets/95891213/87b1f54c-f639-44c1-a13e-a5ceb8abab5f)

But outside of Scryer Playground it works, like in WSL2:

![286333878-eb8b1ead-2e83-4e71-9c48-af2eaa685215](https://github.com/aarroyoc/scryer-playground/assets/95891213/21b84618-f1a8-41a2-9ef1-a760cfb9bcc6)

**Comment by triska** [comment]
Time measuring is not yet possible in the WASM port! In particular, for:

<pre>
t(N) :- '$cpu_now'(N).
</pre>

we get in the WASM port:

<pre>
<b>?- t(N).</b>

[N=_863]
</pre>

**Comment by aarroyoc** [comment]
I sent a PR adding support for $cpu_now in wasm: https://github.com/mthom/scryer-prolog/pull/2186

**Comment by jgarte** [comment]
Hi, should this issue be closed since #2186 was merged?

**Comment by aarroyoc** [comment]
I tried this again and I think we broke this functionality in https://github.com/aarroyoc/scryer-playground/issues/16. Right now it panics with `window global object should be available`. Which may be an undesired side-effect of moving the computation to WebWorkers.

Off-topic: I've seen your lightning talk for ELS2024 in the live stream. It would be amazing to have a similar thing for Prolog too!

**Comment by Jean-Luc-Picard-2021** [comment]
Seems to be impossible to implement, even
after like 12 months, so closing this ticket, right?

**Comment by bakaq** [comment]
This is something I think we can implement. We just need to make stuff like `'$cpu_now'/1` configurable on machine creation, so that we can provide a JS/Wasm/C function pointer that does the necessary work. There are a lot of stuff that I think should be configurable like this, like streams, and Wasm (and therefore Scryer Playground) would benefit a lot from that. Enabling stuff like that is on my roadmap after #2490.
