### ISSUE TITLE
Memory leak in Scryer Prolog

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [aarroyoc/scryer-playground#12]
With limits I get this result:
```
$ ulimit -m 2000000
$ ulimit -v 2000000
$ target/release/scryer-prolog
?- ['program2.p'].
true.
?- between(1,100,_), suite_quiet, fail; true.
Segmentation fault
```
Not ok! Should continue running till the end.

Test program is this here:

[program2.p.log](https://github.com/aarroyoc/scryer-playground/files/13496642/program2.p.log)

**Comment by bakaq** [comment]
Possibly related to https://github.com/mthom/scryer-prolog/issues/950.

**Comment by Jean-Luc-Picard-2021** [comment]
You can try, with the same ulimits:
```
/* Scryer Prolog v0.9.3-97-ga66b93c9 */
?- [user].
app([], X, X).
app([X|Y], Z, [X|T]) :- app(Y, Z, T).
garbage(0, [0]) :- !.
garbage(N, L) :- M is N-1, garbage(M, R), app(R, R, L).
foo :- garbage(12,_), foo.

?- foo.
memory allocation of 2147483648 bytes failed
Aborted
```
On the other hand SWI-Prolog runs and runs and runs:

![thread_monitor](https://github.com/aarroyoc/scryer-playground/assets/95891213/7db32df5-76d4-4cf9-a8ea-d1010524ecf3)

![legend](https://github.com/aarroyoc/scryer-playground/assets/95891213/8a6d1a63-2b3c-4a45-8bf4-33373c864c58)

**Comment by Jean-Luc-Picard-2021** [comment]
Seems to be impossible to implement, even
after like 12 months, so closing this ticket, right?

**Comment by aarroyoc** [comment]
Just earlier this week a new rebis-dev branch was published which improves this aspect of Scryer Prolog
