### ISSUE TITLE
[Feature Request] Permalink generation

### ISSUE THREAD

**Issue by razetime** [aarroyoc/scryer-playground#13]
A way to get the permalink for the code typed so far (one that compresses the code into a URL parameter) would be useful to share scryer programs and share info about bugs.

**Comment by aarroyoc** [comment]
I've added the first version of this! You can already go to the [Scryer Playground](https://play.scryer.pl) and save your code snippets. Here's an [example](https://play.scryer.pl/?snippet=0b5c316f0a0fcfed5e977da719b600a68d2c7aa130fb75a31b350cf9b6be25fbcbffb4850cbc683c16557501aacdcf37551699cef4ab5d7453eb5dd41606cf9e)!

**Comment by razetime** [comment]
looks good to me! I see that it seems to generate a proper, unique permalink for the code, which is very nice.

**Comment by aarroyoc** [comment]
Yes, I developed a small microservice with `library(http/http_server)`. Let's see how it goes
