### ISSUE TITLE
Non-termination of a query freezes the whole site

### ISSUE THREAD

**Issue by bakaq** [aarroyoc/scryer-playground#16]
A query that doesn't terminate, or takes too long to show an answer, freezes the whole site. For example:

```
?- repeat, false. % The whole site freezes.
```

See also #15.

It seems that Scryer is blocking the main thread (the one that renders the interface and handles input), which is Javascript blasphemy. Consider using [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to avoid this.

**Comment by aarroyoc** [comment]
I've published a new version that moves computation to the WebWorker. It also adds support for canceling the current execution. I think it adds a little delay for very simple queries, but it may just be my perception.

**Comment by bakaq** [comment]
Looks good, thanks!

**Comment by bakaq** [comment]
> I think it adds a little delay for very simple queries, but it may just be my perception.

I'm not an UX expert, but I think that the flashing of the "Executing..." message makes short queries feel slower than they really are. A solution is to only show this "loading" message if the query lasts some time (half a second?). I first heard of this concept [here](https://fly.io/phoenix-files/make-your-liveview-feel-faster/).
