### ISSUE TITLE
?- char_code(C, 0). does not work as expected

### ISSUE THREAD

**Issue by triska** [aarroyoc/scryer-playground#18]
Currently, I get:

<pre>
<b>?- char_code(C, 0).</b>

[C=]
</pre>

Whereas on the Scryer toplevel, I get, as expected:

<pre>
<b>?- char_code(C, 0).</b>
   C = '\x0\'.
</pre>

**Comment by bakaq** [comment]
#14  solves this.

**Comment by aarroyoc** [comment]
A version with the new toplevel has been deployed

**Comment by triska** [comment]
Perfect, thank you a lot!
