### ISSUE TITLE
freeze/2 not working correctly?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [aarroyoc/scryer-playground#21]
Tryed to generate primes via freeze/2, but failed to do so:
```
/* Scryer Prolog 0.9.3 */
?- above(2,L),sift(L,R), take(10,R,S), write(S), nl.
   error(instantiation_error,(is)/2).
```
Works fine in SWI-Prolog and Trealla Prolog:
```
/* SWI-Prolog 9.1.21 and Trealla Prolog 2.34.8 */
?- above(2,L),sift(L,R), take(10,R,S), write(S), nl.
[2,3,5,7,11,13,17,19,23,29]
```
Source code:

[primes.p.log](https://github.com/aarroyoc/scryer-playground/files/14045785/primes.p.log)

**Comment by triska** [comment]
Awesome catch! The reason for this phenomenon is an underlying issue in Scryer&nbsp;Prolog itself which is now corrected: https://github.com/mthom/scryer-prolog/issues/2307#issuecomment-1911583997.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, will try again. Wonder how fast freeze/2 is, see also here:

https://github.com/trealla-prolog/trealla/issues/479

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, will try again. Wonder how fast freeze/2 is, see also here:

https://github.com/trealla-prolog/trealla/issues/479

Here is an alternative version delegating the var/1 check to 
freeze/2 itself, it should have an according fast path, right?

[primes2.p.log](https://github.com/aarroyoc/scryer-playground/files/14063183/primes2.p.log)

The alternative version doesn't work for all problems, like
when a variable gets instantiated with a variable. But the present
problem did work in Trealla Prolog with the alternative version.

**Comment by aarroyoc** [comment]
After upgrading to 0.9.4 the playground, this example runs correctly.

**Comment by Jean-Luc-Picard-2021** [comment]
If the example runs correctly, we can close this ticket, right?

**Comment by aarroyoc** [comment]
We usually let the author of the ticket to close it by themself
