### ISSUE TITLE
Transscript of interaction in reverse order

### ISSUE THREAD

**Issue by UWN** [aarroyoc/scryer-playground#3]
Currently in [playground](https://play.scryer.pl/) the interaction is inserted below the typed in query. In this manner, older queries are listed in reverse order. I have seen that style of interaction in Tau first, but it really leads to a confusing transscript.

Suggestion: Reverse the order. Thus one enters a query below and the query+answer is then shown above.

**Comment by aarroyoc** [comment]
I reversed the order
