### ISSUE TITLE
make popcount/1 an evaluable function?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [aarroyoc/scryer-playground#35]
Many Prolog systems have `popcount/1` as an evaluable function.
This seems to be not available in Scryer Prolog. I get this
error, although I imported library(arithmetic):
```
?- ['gridn.p'].
   error(type_error(evaluable,popcount/1),load/1).
```
Thats a pitty, one more obstacle in portable Prolog code.
This is the source code, solving the Numbrix puzzle in Prolog
with the ISO core bitwise operation and a popcount/1 extension:

[gridn.p.log](https://github.com/user-attachments/files/17305547/gridn.p.log)

**Comment by Jean-Luc-Picard-2021** [comment]
P.S.: I know it is hard to make evaluable functions
definable in modules or Prolog text more general.
Especially since executing a Prolog defined evaluable

functions can be non-trivial in terms of stack etc..,
since evaluable functions just like unification etc..
might use other stacks, and therefore mixing with

the Prolog stack can lead to bad performance, because
of some impedence mismatch. But there is a nice compromise, 
for native libraries it might be easier to register 

a new evaluable function.

**Comment by aarroyoc** [comment]
Currently, there's no way to define custom evaluable functions and I think until no "good solution" is found, Scryer is going to take a conservative approach and not allow functions outside the ISO standard.

**Comment by Jean-Luc-Picard-2021** [comment]
The implementation to allow native libraries to register
new evaluable functions is the same as how predicates
are consulted. Take these two files:
```
$ cat > foo.p

test :- hello.

$ cat > bar.p

hello :- write('hello'), nl.
```
If I consult foo.p before bar.p there is a forward reference.
But if I ultimately consult bar.p the forward reference is
resolved. How does a Prolog system do that?
```
$ target/release/scryer-prolog
?- ['foo.p'].
   true.

?- test.
   error(existence_error(procedure,hello/0),hello/0).

?- ['bar.p'].
   true.

?- test.
hello
   true.
```
Now enhance is/2, etc... so that it uses the same resultion 
meachanism, but only for the evaluable function namespace,
and provide a FFI where one can register evaluable functions,

in the evaluable function namespace, eh voila you are done,
makeing your Prolog extensible. Allowing to register evaluable
functions like gdc/2, popcount/1, etc.. outside of the core.

**Comment by Jean-Luc-Picard-2021** [comment]
In the proposal Name resolution is blackbox. It can be
anything, atom table, dynamic lookup, etc.. etc.. There
should be a lot of synergy in every Prolog system using

the same approach for predicates and evaluable functions
concerning their existence. But of course evaluable functions
need special attention to have efficient evaluation.
