### ISSUE TITLE
Intended share behavior?

### ISSUE THREAD

**Issue by jasonhemann** [aarroyoc/scryer-playground#44]
Hi,

What are you hoping `share your snippet!` link will do? More than what's obvious from the name. 
Do you have an intended pastebin service, or are you just planning to copy the buffer to the user's clipboard? Something else?

**Comment by aarroyoc** [comment]
It should store the code in a pastebin like manner, giving you a link so you can reference it later. However, I think the service is not working right now. I'll look into it!

**Comment by aarroyoc** [comment]
It has been working for at least a week. So I think it can be closed

**Comment by jasonhemann** [comment]
Aye aye!
