### ISSUE TITLE
"\n" in output should be translated to HTML linebreaks (BR)

### ISSUE THREAD

**Issue by triska** [aarroyoc/scryer-playground#5]
For example, with the query:

<pre>
?- maplist(portray_clause, ["hello","there"]).
</pre>

I expect to see as output:

<pre>
"hello".
"there".
</pre>

Whereas currently, I see the output all on the same line:

<pre>
"hello". "there". []
</pre>

This would be useful for instance for the famous Sudoku use case, where we query for example:

<pre>
<b>?- problem(2, Rows), sudoku(Rows), maplist(portray_clause, Rows).</b>
</pre>

And expect output such as:

<pre>
[7,8,2,4,3,5,1,9,6].
[6,4,9,8,2,1,7,3,5].
[1,3,5,7,9,6,4,8,2].
[3,7,4,2,1,9,6,5,8].
[9,6,1,5,8,7,2,4,3].
[5,2,8,6,4,3,9,7,1].
[8,5,6,9,7,2,3,1,4].
[2,9,3,1,5,4,8,6,7].
[4,1,7,3,6,8,5,2,9].
</pre>

**Comment by triska** [comment]
Maybe it would suffice to format the output using `<pre>...</pre>`, or with a suitable CSS definition?

**Comment by aarroyoc** [comment]
It should work now

**Comment by triska** [comment]
Awesome, thank you a lot! Now though I get a resized input textbox when I post for example the query:

<pre>
?- length(Ls, 1000), maplist(=(a), Ls).
</pre>

This is because the right-hand window (toplevel) becomes very wide, and the program textbox shrinks.

This also occurs in the Sudoku example I mentioned:

![Screenshot 2023-09-19 at 22 28 02](https://github.com/aarroyoc/scryer-playground/assets/7482140/efcb4c8b-e52e-42f1-b91c-4a34b50a7f9b)

**Comment by aarroyoc** [comment]
I fixed that too

**Comment by triska** [comment]
Perfect, thank you a lot!
