### ISSUE TITLE
#\ is not parsed correctly

### ISSUE THREAD

**Issue by triska** [aarroyoc/scryer-playground#6]
With the following program:

<pre>
:- use_module(library(clpz)).
</pre>

I get:

<pre>
?- <b>#\ 0.</b>
<b>error(syntax_error(missing_quote),read_term/3:3)</b>, unexpected.
true. % expected
</pre>

**Comment by triska** [comment]
I think the issue is the backslash (`\`). For example, with:

<pre>
:- use_module(library(lists)).
:- use_module(library(lambda)).
</pre>

I get:

<pre>
<b>?- maplist(\a^true, Ls).</b>
 error(syntax_error(unexpected_char),read_term_from_chars/3:0).
</pre>

Expected:

<pre>
<b>?- maplist(\a^true, Ls).</b>
   Ls = []
;  Ls = "a"
;  Ls = "aa"
;  Ls = "aaa"
;  ... .
</pre>

**Comment by aarroyoc** [comment]
Sorry for the delay. This should be fixed now

**Comment by triska** [comment]
Thank you a lot!
