### ISSUE TITLE
Most recent answer should remain in view

### ISSUE THREAD

**Issue by triska** [aarroyoc/scryer-playground#9]
Currently, when I post for example `?- true.` many times in a row, then I can no longer see the latest answers when they move out of view after a few interactions, and only exist way down below.

If possible, I would like to automatically see the latest answer, while still being able to easily post queries (i.e., keep the entrybox also in view and in focus).

**Comment by aarroyoc** [comment]
Is it OK the way it is now?

**Comment by triska** [comment]
I think now it is a bit more confusing than before, because we now see the most recent interaction, and then a log of all interactions below that, including the most recent interaction. In particular, when the very first query is posted, we now see the exact same interaction twice. For example, when posting `X = 3`, we go from this:

![Screenshot 2023-11-27 at 21 46 35](https://github.com/aarroyoc/scryer-playground/assets/7482140/bedd8f04-5a97-450a-a48c-2dd4bb70e481)

to this:

![Screenshot 2023-11-27 at 21 46 40](https://github.com/aarroyoc/scryer-playground/assets/7482140/5fedcc6d-b92f-4d51-9292-194cb28b91c2)


Since the most recent interaction is already logged as part of the entire history, would it not suffice to scroll down the history so that the most recent interaction is always in view when a new query is posted and an answer is shown?

**Comment by aarroyoc** [comment]
Good idea! I removed that area and now it scrolls down automatically to the last answer, so it remains in view.

**Comment by triska** [comment]
I think it's now excellent, thank you a lot!
